Add initial RHEL 6 preupg analysis.
oamg/ansible-leapp pull request #53
Opened 2023-05-01 20:02 UTC by jeffmcutter

2023-05-01 21:28 UTC, djdanielsson requested changes

2023-05-01 21:28 UTC, djdanielsson commented on roles/analysis/tasks/main.yml
> +  ansible.builtin.include_tasks: analysis-preupg.yml
rename the file to have rhel6 if it is specifically for rhel 6

2023-05-01 22:00 UTC, djdanielsson approved these changes
LGTM

2023-05-01 22:00 UTC, merged

2023-05-02 12:44 UTC, swapdisk commented on roles/analysis/handlers/main.yml
> +- name: Remove lynx package
@jeffmcutter, why are we removing this package during analysis? Ideally, the analysis role shouldn't be making changes beyond installing the packages required to generate the report.

2023-05-02 15:40 UTC, swapdisk commented on roles/analysis/handlers/main.yml
> +- name: Remove lynx package
Got it, thanks!